

#ifndef OPENCV_CORE_OCL_RUNTIME_CLAMDBLAS_HPP
#define OPENCV_CORE_OCL_RUNTIME_CLAMDBLAS_HPP

#ifdef HAVE_CLAMDBLAS

#include "opencl_core.hpp"

#include "autogenerated/opencl_clamdblas.hpp"

#endif

#endif
