

#ifndef OPENCV_CORE_OCL_RUNTIME_CLAMDFFT_HPP
#define OPENCV_CORE_OCL_RUNTIME_CLAMDFFT_HPP

#ifdef HAVE_CLAMDFFT

#include "opencl_core.hpp"

#include "autogenerated/opencl_clamdfft.hpp"

#endif

#endif
