

#ifndef OPENCV_CORE_OCL_RUNTIME_OPENCL_GL_HPP
#define OPENCV_CORE_OCL_RUNTIME_OPENCL_GL_HPP

#if defined HAVE_OPENCL && defined HAVE_OPENGL

#include "opencl_core.hpp"

#include "autogenerated/opencl_gl.hpp"

#endif

#endif
