#ifndef VISUAL_LAB_QT_LOGGING_H
#define VISUAL_LAB_QT_LOGGING_H

#include <QLoggingCategory>



Q_DECLARE_LOGGING_CATEGORY(labCore)
Q_DECLARE_LOGGING_CATEGORY(labCamera)
Q_DECLARE_LOGGING_CATEGORY(labPipeline)
Q_DECLARE_LOGGING_CATEGORY(labUi)
Q_DECLARE_LOGGING_CATEGORY(labTest)

#endif
